server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
  oauth2:
  client:
    registration:
      google:
        client-id: 1052243205142-53e4hljl8mepbiclik1lk25ngsh9vced.apps.googleusercontent.com
        client-secret: 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
        scope:
          - email
          - profile

  naver:
    client-id: 47SqeiLoZh97vPDQZ60m
    client-secret: aS8eHqq0d9
    scope:
      -name
      -email
    client-name: Naver
    authoriztion-grant-type: authorization_code
    redirect-uri: http://localhost:8080/login/oauth2/code/naver

  provider:
    naver:
      authorization-uri: https://nid.naver.com/oauth2.0/authorize
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user-name-attribute: response # ????? json? response ???? ????.
